name: hardhat test CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Run hardhat test
        continue-on-error: false
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        run: npx hardhat test
